CREATE TABLE `POST`
(
    `PST_NO`    BIGINT NOT NULL AUTO_INCREMENT
 COMMENT '게시글번호',
    `PST_CL_NO`    INT NOT NULL COMMENT '게시글분류번호',
    `TPC_CTG_NO`    VARCHAR(6) NOT NULL COMMENT '주제카테고리번호',
    `PST_TTL`    VARCHAR(240) NOT NULL COMMENT '게시글제목',
    `PST_DISP_CD`    VARCHAR(6) NOT NULL COMMENT '게시글전시코드',
    `TOP_PST_YN`    VARCHAR(1) NOT NULL COMMENT '상단고정여부',
    `WRT_MBR_NO`    BIGINT NOT NULL COMMENT '작성자회원번호',
    `WRT_DTT`    DATETIME NOT NULL COMMENT '작성일시',
    `VIEW_CNT`    INT NOT NULL COMMENT '조회수',
    `CMNT_YN`    VARCHAR(1) NOT NULL COMMENT '댓글가능여부',
    `RCM_YN`    VARCHAR(1) NOT NULL COMMENT '추천가능여부',
    `PST_ST_DTT`    DATETIME NOT NULL COMMENT '게시시작일시',
    `PST_ED_DTT`    DATETIME COMMENT '게시종료일시',
    `DEL_YN`    VARCHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부',
    `REG_NO`    BIGINT NOT NULL COMMENT '등록자',
    `REG_DTT`    DATETIME NOT NULL COMMENT '등록일시',
    `MOD_NO`    BIGINT NOT NULL COMMENT '수정자',
    `MOD_DTT`    DATETIME NOT NULL COMMENT '수정일시',
 PRIMARY KEY ( `PST_NO` )
)
 COMMENT = '게시글';

CREATE UNIQUE INDEX `POST_PK` ON `POST`
( `PST_NO` );


CREATE TABLE `POST_CONTENTS`
(
    `PST_NO`    BIGINT NOT NULL COMMENT '게시글번호',
    `PST_CNTN`    LONGTEXT NOT NULL COMMENT '게시글내용',
 PRIMARY KEY ( `PST_NO` )
)
 COMMENT = '게시글내용';

CREATE UNIQUE INDEX `POST_CONTENTS_PK` ON `POST_CONTENTS`
( `PST_NO` );


CREATE TABLE `TAG`
(
    `PST_NO`    BIGINT NOT NULL COMMENT '게시글번호',
    `TAG_SEQ`    INT NOT NULL COMMENT '태그순번',
    `TAG_NM`    VARCHAR(100) NOT NULL COMMENT '태그명',
 PRIMARY KEY ( `PST_NO`,`TAG_SEQ` )
)
 COMMENT = '태그';

CREATE UNIQUE INDEX `TAG_PK` ON `TAG`
( `PST_NO`,`TAG_SEQ` );
